apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secret
  namespace: tekton-vault
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    vaultSkipTLSVerify: "true"
    roleName: "my-role"
    objects: |
      - objectName: "demo-secret"
        secretPath: "secret/data/my-secret"
        secretKey: "username"
      - objectName: "demo-secret-pass"
        secretPath: "secret/data/my-secret"
        secretKey: "password" 