apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: vault-secret-pipeline-run
  namespace: tekton-vault
spec:
  pipelineRef:
    name: vault-secret-pipeline
  taskRunSpecs:
    - pipelineTaskName: read-secret
      serviceAccountName: pipeline-sa 