apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secret
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "my-role"
    objects: |
      - objectName: "username"
        secretPath: "secret/data/my-secret"
        secretKey: "username"
      - objectName: "password"
        secretPath: "secret/data/my-secret"
        secretKey: "password"
    vaultSkipTLSVerify: "true" 