# yo this is the scc that vault needs to run
# we need this because:
# 1. vault needs to run as a specific user (100)
# 2. needs fsGroup for storage
# 3. openshift's default sccs are too restrictive
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: vault-scc
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:vault:vault
- system:serviceaccount:vault:vault-agent-injector
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret 