global:
  openshift: true
server:
  dev:
    enabled: true
    devRootToken: root
  standalone:
    enabled: true
  serviceAccount:
    name: vault
  extraSecurityContextConstraints:
    - vault-scc
  securityContext:
    runAsUser: 1000830000
    runAsGroup: 1000830000
    fsGroup: 1000830000
injector:
  enabled: true
  serviceAccount:
    name: vault-agent-injector
  securityContext:
    runAsUser: 1000830000
    runAsGroup: 1000830000
    fsGroup: 1000830000